thoughtbot/parity

packaging/development_shim.sh
packaging/production_shim.sh
packaging/staging_shim.sh

The last line of each shim is (e.g.):
```
exec "$SELF_DIR/../lib/ruby/bin/ruby" "$SELF_DIR/../lib/app/bin/staging"
```
Note that this is running `staging` and not passing along any arguments passed
to the shim, so all subcommands are ignored. Running `staging open` is passed
along as just `staging`.
The fix is to pass along arguments passed to the shim with `"$@"`:
```
exec "$SELF_DIR/../lib/ruby/bin/ruby" "$SELF_DIR/../lib/app/bin/staging" "$@"
```

Pass subcommands to shims

---

lib/parity/environment.rb
spec/environment_spec.rb

Use the alternate form of `Kernel.system` which
respects the quoting of the arguments provided
to parity.
Before:
```
> production pg:psql -c "select count(*) from users;"
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `heroku pg:psql -c select count(*) from users; --remote production'
```
After:
```
> production pg:psql -c "select count(*) from users;"
---> Connecting to HEROKU_POSTGRESQL_AQUA_URL (DATABASE_URL)
count
-------
10201
```

Support multiword arguments to heroku CLI

---

README.md
lib/parity/environment.rb
spec/environment_spec.rb

When a user runs `ENVIRONMENT deploy`
Parity will:
- fetch the git remote for the environment
- check if there are changes in `db/migrate`
which will be pushed.
- push local master branch to remote master
- run parity's migrate command if needed.

Add "deploy" subcommand

---

lib/parity/usage.rb

Changes made in 3b9378cab79b4d2b0000766ccaec1a2bbde83c8d broke
the regex that took the Usage slice out of README.md. This change to the
regex results in the correct excerpt being pulled.

Fix usage problem due to README changes

---

lib/parity/backup.rb
lib/parity/environment.rb
spec/backup_spec.rb
spec/environment_spec.rb

We attempted to do this in 5e789c3, but Heroku Toolbelt had some missing
functionality with respect to the new `pg:backups` syntax, and our code
retained the `--expire` flag, which is now automatic and no longer
allowed.
This change requires that users have version 3.32.0 of the Heroku
Toolbelt installed, but the old `pgbackups:capture / pgbackups:restore`
syntax and addon are being retired in the first week of May 2015, so we
need to do this to move on in any event (users who don't upgrade won't
be able to use the old parity either).
Close #29.

Use new pg:backups syntax

---

README.md
lib/parity/environment.rb
spec/environment_spec.rb

Why:
* `log2viz` was useful before Heroku's application metrics existed.
https://devcenter.heroku.com/articles/metrics
* Other alternatives include New Relic and Skylight.
How it addresses the need:
* Remove the feature.

Remove log2viz

---

lib/parity/environment.rb
spec/environment_spec.rb

When working on a non-trivial feature, it is often desirable to be able
to push the unmerged feature branch to the staging environment (or a
feature-specific environment) without merging it to master (on many
projects master is considered "ready to deploy").
This change alters the `deploy` subcommand for non-production
environments to push a non-master branch to the desired Heroku
environment's master branch (`git push staging` will actually push your
feature branch to a useless feature branch that doesn't get deployed on
staging) so that feature branches can be evaluated
without requiring a merge to master that might then have to be undone or
accidentally deployed to production.

Deploy feature branches to staging or feature envs

---

lib/parity/backup.rb
spec/backup_spec.rb

Heroku's CLI tool for `pg:pull` now expects there to be no development
database in place, as it runs `createdb` to attempt to create the
development database before restoring the remote backup locally.
This change runs `dropdb` to clear out the development database before
using Heroku's `pg:pull` to bring the remote backup down to the
development environment.
Close #47.

Drop development database before `development restore`

---

spec/parity/backup_spec.rb
spec/parity/environment_spec.rb
spec/parity/usage_spec.rb

Moving these files into `spec/parity` allows developers to move back and
forth between specs and code using alternate file mappings. It also
makes the layout of `spec` more closely follow the same structure as
`lib` to make navigating the codebase easier.

Move spec files to match layout of `lib`

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

When using Parity with a Python project, the `deploy` subcommand was
causing harmless but annoying error messages when the deploy step for
running migrations was attempted. This change checks that the `rake`
command is available to the application and that the application has a
`db:migrate` task defined (using Rake's `-n` switch for a "dry run").
Other changes:
* Stub out `Kernel.system` in environment specs to always return true
unless explicitly told otherwise. Many of our specs stubbed out
`.system` just to keep execution moving forward. Stubbing out across
all the specs also prevents accidental execution of commands in a spec
where stubbing was not set up.
Fix #49.

Don't attempt to migrate on deploy for non-Rails apps

---

README.md

The `README.md` had a slight mistake concerning restoring a development database to a staging environment. This pull request takes care of that.

Update to correct restoration of db to staging from development

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

v0.9.0 broke `deploy` in two ways. The first is that migrations were
being checked after the deploy completed, which resulted in the check
for diffs in `db/migrate` always finding no differences. This change
reverts to the prior pattern of caching whether migrations are pending
at the start of `deploy` before pushing to Heroku.
The second is that the check for `rake` would raise an exception if a
user's local bundle wasn't installed, as the shell command would return
a failing status. `Kernel.system` can return `true`, `false`, or `nil`,
but `Kernel.exit` can't accept `nil` as an argument.
`Parity::Environment#run` will now always return a boolean value so that
`Kernel.exit` receives an appropriate argument.
Fix #61.

Fix `deploy` problems in 0.9.0

---

README.md

In df296fe6e77698fe4522b120944621667b1dcbd3 we added the capability to
push non-master branches to staging or other feature environments for
testing. Pushes to non-production environments are forced in case a
developer has been squashing commits.
This change updates the README to clarify that pushes are permitted from
non-master branches to non-production environments.
Close #56.

Update docs on deploying non-master branches

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

It is not used anywhere in the codebase.

Remove stale pg_restore method

---

README.md
lib/parity/environment.rb
spec/parity/environment_spec.rb

I find `development restore production` to be confusing at times. I find that I end up looking up the proper syntax quite a bit. I aliased `restore` with `restore_from` because I feel that it describes what I'm trying to accomplish better.
* Private method for methodizing subcommands
* Test it good!

Alias restore with restore-from for clarity

---

Gemfile
README.md
lib/parity.rb
lib/parity/environment.rb
parity.gemspec
spec/parity/environment_spec.rb

Several reports have matched #72, which was affecting the `restore`
command for some users. The cause turned out to be local folder names
not matching the name of the Heroku app. Now that Heroku tracks Git
remotes, we can take advantage of the Git remote to correctly identify
the app name even the local folder name doesn't match.
While this requirement has existed for the entirety of Parity's
existence, it stopped being a problem for most commands once Heroku
introduced remotes. I inadvertently reintroduced this requirement in
ad2c21a42fb85bd00ec58d7326725f0a1d5a7771 when we started automatically
bypassing confirmation arguments for restores to non-production
environments.
Fix #72.

Parse git remote name to determine Heroku app

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

In 10574fe we began using the Git remote address to determine the name
of the Heroku application. The change did not correctly handle Git
remotes that use the HTTPS protocol, which Heroku supports.
This change updates the address parsing to handle both `git://` and
`https://` remotes.

Correctly parse HTTPS Heroku remotes

---

README.md

Updated the README to give an example of adding remotes to Heroku. Thought it would be nice to see an example here to prevent someone from having to look it up.

README - Add remotes example

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

In #79, @bernerdschaefer raised the issue that for long-running
processes like log-tailing and consoles that parity was responding to
Control-C and terminating the process rather than letting the remote
session handle the input.
This change updates `Environment#run_via_cli` to use `Kernel.exec`
rather than `Kernel.system`, which replaces the current process with the
desired command. We aren't replacing all uses of `Kernel.system`, as
some of our commands are multi-step and would not successfully complete
if interrupted by an non-final command being invoked though `exec`. This
solution should give better results for consoles and other long-running
tasks.
http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-exec
Close #79.

Use `Kernel.exec` for long-running processes

---

UPGRADING
parity.gemspec

Rubygems should be used to install dependencies, not to distribute
command-line tools (other than perhaps those highly-coupled to a
specific Ruby version). Our packaging with Travelling Ruby allows us to
distribute Parity via popular package managers or for users to compile
and install locally.
This change removes the gemspec statement that installs the
`development`, `production`, and `staging` executables through Rubygems.
Those files remain available in packaging, and will be installed by apt
and Homebrew.
Close #77.

[blocked by #97] Don't install executables via Rubygems

---

lib/parity/backup.rb
parity.gemspec
spec/parity/backup_spec.rb

> Run the most time-consuming parts of pg_restore — those which load
> data, create indexes, or create constraints — using multiple
> concurrent jobs. This option can dramatically reduce the time to
> restore a large database to a server running on a multiprocessor
> machine.
> Each job is one process or one thread, depending on the operating
> system, and uses a separate connection to the server.
> The optimal value for this option depends on the hardware setup of the
> server, of the client, and of the network. Factors include the number
> of CPU cores and the disk setup. A good place to start is the number
> of CPU cores on the server, but values larger than that can also lead
> to faster restore times in many cases. Of course, values that are too
> high will lead to decreased …

Run pg_restore using multiple concurrent jobs

---

lib/parity/backup.rb
lib/parity/environment.rb
spec/parity/backup_spec.rb
spec/parity/environment_spec.rb

It looks like heroku has updated some `pg:backups` commands https://devcenter.heroku.com/articles/heroku-postgres-backups
* Updates heroku PG CLI commands as of 08/dec/2016

fix/ add-heroku-pg-updates

---

Rakefile
lib/parity/version.rb
packaging/development_shim.sh
packaging/production_shim.sh
packaging/staging_shim.sh

Traveling Ruby is no longer receiving updates, and is locked on a
version of Bundler that causes an update to `Gemfile.lock` when `bundle
install` is run on installed systems, which causes permission problems
on client users' machines.
We stopped using gem dependencies in Parity in 5704201, but still had
pieces of our packaging that were there solely to support gem
dependencies.
This change brings our Rakefile back to the original setup for Traveling
Ruby by @joelq in 7916985 along with @gabebw's shim fixes in 89be4ad. We
still plan to migrate away from Traveling Ruby, but these changes are
needed to get a valid, working packaged version of Parity on client
machines to comply with the new Heroku CLI format.
One update has been made since those prior Rakefile and shim versions,
which is to …

Packaging: Remove Bundler from packaging

---

lib/parity.rb
lib/parity/backup.rb
lib/parity/environment.rb
lib/parity/heroku_app_name.rb
spec/parity/backup_spec.rb
spec/parity/environment_spec.rb
spec/parity/heroku_app_name_spec.rb

Heroku's `pg:push` CLI no longer accepts the `--confirm` argument, as it
expects the remote database to already be reset before overwriting it
with a backup.
Before restoring to a remote environment, we reset the remote database
with `pg:reset`. We will pass a confirm argument to `pg:reset`. To
accomplish this, the mechanism to determine the remote application name
(not the git remote) has been extracted into its own object.
Fix #128.

Heroku-CLI change: don't pass `--confirm` to `pg:push`

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

When restoring a remote backup to development, if an application doesn't
have a `tmp` folder (either because it wasn't in source control or the
app never has one), we can't download the backup file from Heroku.
This change uses `mkdir -p` to create the directory (if needed) before
downloading the backup to the local machine.
Close #130.

development restore: ensure a tmp directory exists

---

lib/parity/version.rb

Heroku Toolbelt has been replaced by / renamed to Heroku CLI.
It is installed with `brew install heroku`. See:
https://devcenter.heroku.com/articles/heroku-cli#macos
* Upgrade Ruby version for contributors.
* Update release documentation for contributors.
Related:
https://github.com/thoughtbot/laptop/commit/3b7845b849830033e87617b470d8dd64c925e732
https://github.com/thoughtbot/laptop/commit/0636eea1983af478037fd75a9519a92f9f18a81f

Version 2.2.1

---

RELEASING.md

We are not using Traveling Ruby since ea23f26.
Describe the new process!

Update release documentation for contributors

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

This change adds a flag to the `dropdb` command so that we don't issue
an error if the local development database doesn't exist when we try to
drop it. A notice is issued by PG, but execution will continue.
PG docs: https://www.postgresql.org/docs/9.3/static/app-dropdb.html
cc: #137

Use `--if-exists` option with `dropdb`

---

.github/issue_template.md
README.md

This template will help users potentially troubleshoot parity issues
themselves and will provide us with more information about issues that
we frequently request.
related: #137 
cc: @croaky

Create issue template

---

README.md

I spent a bit of time looking for a `NEWS.md` file and then remembered to check the releases page. Hopefully this README change will help save other people some time.
(Another idea: create a `NEWS.md` file that just contains a link to the releases page.)

Point people to the releases page

---

parity.gemspec

This change will keep the gem from being tied specifically to one person
in Rubygems.

Update email to point to general thoughtbot account

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

In #143, we got a report that because `Etc.nprocessors` was not
implemented until Ruby 2.2 that Ruby 2.1 users were unable to execute
`development restore`, which leverages that method to determine how many
parallel processes to use when restoring the backup from the downloaded
dump.
This change implements a check to see if `Etc.nprocessors` is available.
In the event that it's not, we'll default to two parallel processes. We
will plan to sunset this change in July 2018, giving users on Ruby 2.1,
which has been EOLed, six months to move on.
Close #143.

Allow pre-2.2 Rubies to execute `development restore`

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

This change updates the Redis subcommand to use `redis-cli`'s `-u`
argument, letting `redis-cli` parse the URL rather than parsing it into
pieces in Parity.
https://redis.io/topics/rediscli#host-port-password-and-database

Use redis-cli `-u` argument rather than splitting URL

---

README.md
bin/pr_app
lib/parity/environment.rb
spec/parity/environment_spec.rb

This change adds a `pr_app` executable that can be used to run commands
on a review application that is part of the same Heroku Pipeline as the
application on the `staging` Git remote. If you had a staging application
called `my-staging-app`, and a review application whose Heroku
application name was `my-staging-app-pr-1234`, you would tail the logs
with:
```shell
pr_app 1234 tail
```
Review applications don't get an automatic local Git remote, but because
they share a name with the staging application, we can leverage the
naming scheme to build up an app name.

Add `pr_app` executable for running Heroku CLI commands on review apps

---

README.md
lib/parity/environment.rb
spec/parity/environment_spec.rb

This change removes code that automatically runs migrations on
deployment. Heroku's recommended approach for automatic migrations on
deploy is to use [Release Phase] tasks, which avoids an unnecessary
application restart (the app launch is after the release phase is run).
Applications that can't use release phase tasks for deployment can use a
`bin/deploy` script similar to the one included in [Suspenders].
This approach removes some Rails-specific code, which brings Parity closer to
being less-Rails focused (the only remaining Rails-specific commands
would be `migrate` and `console`). As a breaking change, this commit would
require a major version bump in its first release.
Fix #104
cc: #115
[Release Phase]: https://devcenter.heroku.com/articles/release-phase
[Suspenders]: …

Don't migrate on deploy

---

lib/parity/environment.rb
spec/parity/backup_spec.rb
spec/parity/environment_spec.rb

We had some private and spec helper method cruft left over from removed
features or changed implementations. This commit removes them.

Remove unused methods

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

This change updates the local development restore operation to update the
`ar_internal_metadata` table if it's present, setting the environment
value to `development`.
Previously, failing to update the environment metadata would result in a potentially alarming error that might cause users to believe they were about to perform a destructive operation against their production database when what was actually happening was that the development database was a snapshot taken from production.
If the table is not present (either for older Rails applications or
non-Rails applications), this anonymous PG function will no-op.
Fix #147

Update ar_internal_metadata after remote restore

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

The previous attempt in e5e025a to mark the `ar_internal_metadata`
environment row as non-production does not work reliably. The change
here fixes the issue with a slightly more brute-force approach, but one
that does not require capabilities beyond pure SQL.
If the `ar_internal_metadata` table does not exist, we'll create a blank
one with no rows. The following update operation will no-op.

Use different approach for marking `ar_internal_metadata` on restore

---

bin/pr_app
lib/parity/version.rb
parity.gemspec

The `pr_app` command was broken in two ways. First, it had a mismatching
argument name for the app/environment flag, resulting in an error
whenever it was called. Second, it was missing the `-pr-` as part of the
Heroku review app name, so it would never find the correct application.
These changes are hard to test with an executable vs. a more OO-based
piece of code, but this change was tested against a real application and
worked correctly.

Fix pr_app executable

---

bin/pr_app

Heroku will truncate the name of your application to 22 characters before using it as your review app prefix.
Fixes #164

Heroku truncates app name to create prefix

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

The combination of Bundler 2, Heroku's Ruby buildpack, and Rails' own
binstubs for Rails 5.2 appears to cause a conflict when starting the
console for an application bundled with Bundler 2.x.
```
% production console
Running rails console on ⬢ app-production... up, run.5165 (Standard-1X)
You must use Bundler 2 or greater with this lockfile.
```
The solution is to invoke the console with `bundle exec`, which gets
around the mismatch of Bundler 1.x and 2.x and blocks the Rails console
from starting.

Use bundle exec when starting remote console

---

lib/parity/environment.rb
spec/parity/environment_spec.rb

The `console` subcommand can't take arguments, which prevents the easy
use of the `--sandbox` feature on staging and production consoles to
check things with confidence that production data isn't being
accidentally changed.
This change appends post-`console` arguments as arguments on Heroku.

Allow passing arguments to `console` subcommand

---

README.md
lib/parity/backup.rb
lib/parity/environment.rb
spec/parity/backup_spec.rb
spec/parity/environment_spec.rb

Per [this issue](https://github.com/thoughtbot/parity/issues/175), right now Parity's default behavior is to attempt to parallelize the `pg_restore` task across multiple cores.  This was causing some parts of the restore op to happen out-of-order, in which case the affected jobs would fail and the restore op as a whole would end unsuccessfully, leaving the DB in a semi-restored state.
This PR removes the default to parallelization, and replaces it with a command line flag which lets the user opt in to parallelization.  The default is now to run `pg_restore` in a single-threaded fashion.

Replace automatic parallelization of backup jobs with opt-in

---

lib/parity/backup.rb
spec/parity/backup_spec.rb

I noticed some output when restoring my database:
```
pg_restore: dropping TABLE geographic_areas
pg_restore: from TOC entry 266; 1259 16503 TABLE geographic_areas uf1mu7mdqgl0dj
pg_restore: error: could not execute query: ERROR:  table "geographic_areas" does not exist
Command was: DROP TABLE "public"."geographic_areas";
```
It looks like the source of the output was the `--clean` flag:
```
--clean
Clean (drop) database objects before recreating them. (Unless
--if-exists is used, this might generate some harmless error messages,
if any objects were not present in the destination database.)
```
https://www.postgresql.org/docs/current/app-pgrestore.html
As the docs say, these errors are harmless, but noisy.
We don't need the `--clean` flag because the commands Parity runs were:
```
dropdb …
```

Don't use --clean flag with pg_restore

---

README.md
lib/parity/environment.rb
spec/parity/environment_spec.rb

Resolves #184 
Heroku has enabled pushing to main by default in a backwards compatible manner (does not affect master branches): https://devcenter.heroku.com/changelog-items/1829
The change checks for the presence of `main` and the absence of `master` -- setting the branch ref appropriately.
Avoids manual / global git configs and doesn't break projects where `master` is still the default branch.

Feature: #deploy to main or master refs

---

bin/pr_app

Heroku has a 20 character limit on review app unique identifiers (see below), but code to generate the `pr_app` prefix from the staging remote grabs 22 characters.

Update pr_app character limit

---

README.md
RELEASING.md

Since Travelling Ruby is no longer supported, it's no longer feasible
for us to package a self-contained release of Parity that runs
independently of local Rubies. This change acknowledges our trailing
support of Homebrew- and apt-installed Parity and encourages
installation of the Rubygem version instead.
We will remove for formula from thoughtbot's Homebrew formulae in a
subsequent change.

Drop non-Rubygem installs

---

README.md
lib/parity/environment.rb
spec/parity/environment_spec.rb

Heroku now offers their own `redis:cli` subcommand, making this
unnecessary.
This change will require a major release as we're removing the feature
entirely.

Drop `redis-cli` command

---

lib/parity/backup.rb

Updated the backup code and added the `aliases: true` option to `YAML.load`. This allows Psych to properly load a `database.yml` file with aliases in newer Rubies.
Fixes #196

Add aliases: true when loading database.yml in newer Rubies
